version: '3'

tasks:
  gitleaks:
    desc: Run gitleaks with repo config
    cmds:
      - gitleaks detect --config .gitleaks.toml

  proposal:
    desc: Build the proposal PDF
    cmds:
      - cd THERAPY && latexmk -pdf proposal.tex