name: gitleaks
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --config=.gitleaks.toml
